[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# Enable Python runtime for our function
[functions."player-stats-sportsipy"]
  runtime = "python3.11"
  included_files = ["api/requirements.txt"]

# Netlify will auto-install from this file if present in repo root or function dir.
# We'll keep it at api/requirements.txt and reference it above.

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
  force = true

# Route stats to Python Sportsipy function
[[redirects]]
  from = "/api/player-stats"
  to = "/.netlify/functions/player-stats-sportsipy"
  status = 200
  force = true

# Serve HTML files directly
[[redirects]]
  from = "/:page.html"
  to = "/:page.html"
  status = 200

