[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[functions."api-player-stats-py"]
  runtime = "python3.11"
  included_files = ["api/requirements.txt"]

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
  force = true

# Route stats to Python (Sportsipy)
[[redirects]]
  from = "/api/player-stats"
  to = "/api/player-stats.py"
  status = 200
  force = true

# Serve HTML files directly
[[redirects]]
  from = "/:page.html"
  to = "/:page.html"
  status = 200

