[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
  force = true

# Serve HTML files directly
[[redirects]]
  from = "/:page.html"
  to = "/:page.html"
  status = 200

# Fallback to index.html for other paths
[[redirects]]
  from = "/:path*"
  to = "/index.html"
  status = 200
